//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public cart()
        {
            this.cartdetails = new HashSet<cartdetail>();
        }
    
        public int userId { get; set; }
        public Nullable<int> quantityBuy { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<cartdetail> cartdetails { get; set; }
    }
}
