//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartdetail
    {
        public int Id { get; set; }
        public Nullable<int> cartId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> quantityBuy { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual product product { get; set; }
    }
}
