//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> productId { get; set; }
    
        public virtual orderr orderr { get; set; }
        public virtual product product { get; set; }
    }
}
