//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderr
    {
        public orderr()
        {
            this.orderdetails = new HashSet<orderdetail>();
            this.payments = new HashSet<payment>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<payment> payments { get; set; }
    }
}
