//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<float> totalPrice { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> creaditCardId { get; set; }
    
        public virtual creditcard creditcard { get; set; }
        public virtual orderr orderr { get; set; }
    }
}
