//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class pbl3Entities : DbContext
    {
        public pbl3Entities()
            : base("name=pbl3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cart> carts { get; set; }
        public DbSet<cartdetail> cartdetails { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<creditcard> creditcards { get; set; }
        public DbSet<image> images { get; set; }
        public DbSet<orderdetail> orderdetails { get; set; }
        public DbSet<orderr> orderrs { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<person> people { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<trademark> trademarks { get; set; }
        public DbSet<user> users { get; set; }
    
        public virtual int CreateNewUser(string name, string sex, Nullable<int> phone, string address, string username, string emailn, string password, string status, Nullable<int> idrole)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var phoneParameter = phone.HasValue ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var emailnParameter = emailn != null ?
                new ObjectParameter("emailn", emailn) :
                new ObjectParameter("emailn", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var idroleParameter = idrole.HasValue ?
                new ObjectParameter("Idrole", idrole) :
                new ObjectParameter("Idrole", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateNewUser", nameParameter, sexParameter, phoneParameter, addressParameter, usernameParameter, emailnParameter, passwordParameter, statusParameter, idroleParameter);
        }
    }
}
