//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.cartdetails = new HashSet<cartdetail>();
            this.images = new HashSet<image>();
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> trademarkId { get; set; }
        public string description { get; set; }
        public Nullable<float> price { get; set; }
        public string Status { get; set; }
        public string infoProduct { get; set; }
        public Nullable<int> quantityRemain { get; set; }
    
        public virtual ICollection<cartdetail> cartdetails { get; set; }
        public virtual category category { get; set; }
        public virtual ICollection<image> images { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual trademark trademark { get; set; }
    }
}
