//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trademark
    {
        public trademark()
        {
            this.products = new HashSet<product>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
