//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.orderrs = new HashSet<orderr>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public Nullable<int> phone { get; set; }
        public string address { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public Nullable<int> Idrole { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual ICollection<orderr> orderrs { get; set; }
        public virtual role role { get; set; }
    }
}
